version: 2
updates:
  - package-ecosystem: "yarn"
    directory: "/" # Location of package manifests
    schedule:
      interval: "weekly"
    commit-message:
      prefix: fix
      prefix-development: chore
      include: scope
